# Generated by Django 2.1 on 2019-05-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='uid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
